### ISSUE TITLE
New-GSAPrivateAccessApp Connector Group setting does not apply

### ISSUE THREAD

**Issue by Altec6** [andres-canello/GlobalSecureAccess.ps#1]
When using the New-GSAPrivateAccessApp function the new GSA Enterprise application is created, but the connector group is set to Default when reviewed from the Entra GUI.

Example (ID numbers have been simplified):

New-GSAPrivateAccessApp -AppName "Test App" -ConnectorGroupID 1-2-3-4-5

**Comment by andres-canello** [comment]
Fixed! thanks for reporting

**Comment by Altec6** [comment]
Thanks for your work on this and the quick turn around!
